### PR TITLE
29 Link Redux to search UI and add mock config

### PR DESCRIPTION
**Pull request by rogup**
#### What? Why?

Related to issue #29 

This PR links up the new search panel to Redux and adds some mock config to populate the panel.

The directory panel UI needs to be fixed to use buttons rather than links before it can be hooked up to Redux.

Note that the labels for the filters are still just the field IDs, logic needs to be added for the translation of these IDs into text.

#### What should we test?

- Open the search panel and see the drop-down for each filter option.
- Change language to French by adding `lang=fr` to the URL query params and check that the filter options are now in french.

#### Checklist

- [x] Updated or added any necessary docs in `docs/`
- [x] Added UTs
- [x] Checked that all automated tests pass

### CODE REVIEW

**Comment by rogup** [comment]
@ms0ur1s Please could you review the things that I've added to this branch since the commit that you added? Please let me know if there's anything that you'd like explaining, and once you're happy with the changes, we can merge this in main and deploy it for the demo.

**Comment by rogup** [comment]
I will also add some more UTs tomorrow, since we should add some tests for the Redux selector logic in searchSlice

**Comment by rogup** [comment]
@ms0ur1s since you're away for a few days, I've merged this so we can get Demo 1 out, but please still give this a review and I can make changes in a separate PR

**Comment by ms0ur1s** [comment]
@rogup, will do man. I'll give it a look before I merge create a branch for the MUI component switch

**Comment by ms0ur1s** [comment]
@rogup, when I try to run the back-end I receive the below error, what am I doing wrong.
image

**Comment by ms0ur1s** [comment]
As per the above I can't get the back-end to run at the moment (most likely my own fault), but there a few UI idiosyncrasies that I spotted so I'll make a quick branch to fix these. I'll add details and the branch name below.

**Comment by ms0ur1s** [comment]
@rogup, although I don't have the back-end running, the updates are looking amazing. Great work! It's so good to see all the piece's starting to connect.

**Comment by wu-lee** [comment]
> @rogup, when I try to run the back-end I receive the below error

That command works for me... Looking at your screenshot I see the version of node reported as 18.18.0 - from this and the error, I think you likely need to be using the one specified in `.tool-versions` - 22.4.1. Mentioned in the docs here but maybe not well highlighted: https://github.com/DigitalCommons/mykomap-monolith/blob/main/docs/deployment.md

To get this on Linux, best use ASDF, instructions here. You also need the nodejs plugin for ASDF. This may require re-starting your terminal to work.

https://asdf-vm.com/guide/getting-started.html

Finally you need to:

    asdf install nodejs 22.4.1

**Comment by ms0ur1s** [comment]
> > @rogup, when I try to run the back-end I receive the below error
> 
> That command works for me... Looking at your screenshot I see the version of node reported as 18.18.0 - from this and the error, I think you likely need to be using the one specified in `.tool-versions` - 22.4.1. Mentioned in the docs here but maybe not well highlighted: https://github.com/DigitalCommons/mykomap-monolith/blob/main/docs/deployment.md
> 
> To get this on Linux, best use ASDF, instructions here. You also need the nodejs plugin for ASDF. This may require re-starting your terminal to work.
> 
> https://asdf-vm.com/guide/getting-started.html
> 
> Finally you need to:
> 
> ```
> asdf install nodejs 22.4.1
> ```

Thanks @wu-lee, I'll give this a try.

**Pull request merged**
